sub = [20,22,25,37,45,39,20,20,20]
#sub = ["c" , "c++" , "java" , "python"]
#sub = list(sub)
#print(type("python" in sub))
#sub.append("js")
#sub.append("android")
#sub.insert(0,"html")
#sub.insert(1,"css")
#sub.reverse()
#sub.pop()
#print(sub)
#print(sub [2])
#print(len(sub))
#sub.insert(2,"os")
#print(sub)
#sub.index(4)
#print(sub)
#sub.pop()
#print(sub)
pop = sub.count(20)
print(pop)
sub.insert(2,"js")
print(sub)